var allMice = [
    { "id": 1, "name": "Abominable Snow", "unique": "Abominable Snow Mouse" },
    { "id": 2, "name": "Acolyte", "unique": "Acolyte Mouse" },
    { "id": 3, "name": "Aged", "unique": "Aged Mouse" },
    { "id": 4, "name": "Alchemist", "unique": "Alchemist Mouse" },
    { "id": 5, "name": "Alnilam", "unique": "Alnilam Mouse" },
    { "id": 6, "name": "Alnitak", "unique": "Alnitak Mouse" },
    { "id": 7, "name": "Aquos", "unique": "Aquos Mouse" },
    { "id": 8, "name": "Archer", "unique": "Archer Mouse" },
    { "id": 9, "name": "Assassin", "unique": "Assassin Mouse" },
    { "id": 10, "name": "Balack the Banished", "unique": "Balack the Banished" },
    { "id": 11, "name": "Bandit", "unique": "Bandit Mouse" },
    { "id": 12, "name": "Bat", "unique": "Bat Mouse" },
    { "id": 13, "name": "Bear", "unique": "Bear Mouse" },
    { "id": 14, "name": "Beast Tamer", "unique": "Beast Tamer Mouse" },
    { "id": 15, "name": "Berserker", "unique": "Berserker Mouse" },
    { "id": 16, "name": "Big Bad Burroughs", "unique": "Big Bad Burroughs Mouse" },
    { "id": 17, "name": "Bionic", "unique": "Bionic Mouse" },
    { "id": 18, "name": "Birthday", "unique": "Birthday Mouse" },
    { "id": 19, "name": "Black Mage", "unique": "Black Mage Mouse" },
    { "id": 20, "name": "Black Widow", "unique": "Black Widow Mouse" },
    { "id": 21, "name": "Bottled", "unique": "Bottled Mouse" },
    { "id": 22, "name": "Briegull", "unique": "Briegull Mouse" },
    { "id": 23, "name": "Brimstone", "unique": "Brimstone Mouse" },
    { "id": 24, "name": "Brown", "unique": "Brown Mouse" },
    { "id": 25, "name": "Buccaneer", "unique": "Buccaneer Mouse" },
    { "id": 26, "name": "Burglar", "unique": "Burglar Mouse" },
    { "id": 27, "name": "Candy Cane", "unique": "Candy Cane Mouse" },
    { "id": 28, "name": "Captain", "unique": "Captain Mouse" },
    { "id": 29, "name": "Caretaker", "unique": "Caretaker Mouse" },
    { "id": 30, "name": "Hapless Marionette", "unique": "Hapless Marionette" },
    { "id": 31, "name": "Cavalier", "unique": "Cavalier Mouse" },
    { "id": 32, "name": "Centaur", "unique": "Centaur Mouse" },
    { "id": 33, "name": "Chameleon", "unique": "Chameleon Mouse" },
    { "id": 34, "name": "Champion", "unique": "Champion Mouse" },
    { "id": 35, "name": "Chitinous", "unique": "Chitinous Mouse" },
    { "id": 36, "name": "Christmas Tree", "unique": "Christmas Tree Mouse" },
    { "id": 37, "name": "Clockwork Samurai", "unique": "Clockwork Samurai Mouse" },
    { "id": 38, "name": "Conjurer", "unique": "Conjurer Mouse" },
    { "id": 39, "name": "Conqueror", "unique": "Conqueror Mouse" },
    { "id": 40, "name": "Cook", "unique": "Cook Mouse" },
    { "id": 41, "name": "Core Sample", "unique": "Core Sample Mouse" },
    { "id": 42, "name": "Costumed Tiger", "unique": "Costumed Tiger Mouse" },
    { "id": 43, "name": "Cowbell", "unique": "Cowbell Mouse" },
    { "id": 44, "name": "Cupid", "unique": "Cupid Mouse" },
    { "id": 45, "name": "Curious Chemist", "unique": "Curious Chemist Mouse" },
    { "id": 46, "name": "Cyclops", "unique": "Cyclops Mouse" },
    { "id": 47, "name": "Dancer", "unique": "Dancer Mouse" },
    { "id": 48, "name": "Davy Jones", "unique": "Davy Jones Mouse" },
    { "id": 49, "name": "Defender", "unique": "Defender Mouse" },
    { "id": 50, "name": "Demolitions", "unique": "Demolitions Mouse" },
    { "id": 51, "name": "Derr Chieftain", "unique": "Derr Chieftain Mouse" },
    { "id": 52, "name": "Derr Lich", "unique": "Derr Lich Mouse" },
    { "id": 53, "name": "Diamond", "unique": "Diamond Mouse" },
    { "id": 54, "name": "Dojo Sensei", "unique": "Dojo Sensei" },
    { "id": 55, "name": "Draconic Warden", "unique": "Draconic Warden Mouse" },
    { "id": 56, "name": "Dragon", "unique": "Dragon Mouse" },
    { "id": 57, "name": "Drummer", "unique": "Drummer Mouse" },
    { "id": 58, "name": "Dumpling Chef", "unique": "Dumpling Chef Mouse" },
    { "id": 59, "name": "Dwarf", "unique": "Dwarf Mouse" },
    { "id": 60, "name": "Eagle Owl", "unique": "Eagle Owl Mouse" },
    { "id": 61, "name": "Eclipse", "unique": "Eclipse Mouse" },
    { "id": 62, "name": "Elder", "unique": "Elder Mouse" },
    { "id": 63, "name": "Elf", "unique": "Elf Mouse" },
    { "id": 64, "name": "Elub Chieftain", "unique": "Elub Chieftain Mouse" },
    { "id": 65, "name": "Elub Lich", "unique": "Elub Lich Mouse" },
    { "id": 66, "name": "Elven Princess", "unique": "Elven Princess Mouse" },
    { "id": 67, "name": "Enslaved Spirit", "unique": "Enslaved Spirit Mouse" },
    { "id": 68, "name": "Escape Artist", "unique": "Escape Artist Mouse" },
    { "id": 69, "name": "Fairy", "unique": "Fairy Mouse" },
    { "id": 70, "name": "Fencer", "unique": "Fencer Mouse" },
    { "id": 71, "name": "Fetid Swamp", "unique": "Fetid Swamp Mouse" },
    { "id": 72, "name": "Fiddler", "unique": "Fiddler Mouse" },
    { "id": 73, "name": "Fiend", "unique": "Fiend Mouse" },
    { "id": 74, "name": "Finder", "unique": "Finder Mouse" },
    { "id": 75, "name": "Flying", "unique": "Flying Mouse" },
    { "id": 76, "name": "Foxy", "unique": "Foxy Mouse" },
    { "id": 77, "name": "Frog", "unique": "Frog Mouse" },
    { "id": 78, "name": "Frosty Snow", "unique": "Frosty Snow Mouse" },
    { "id": 79, "name": "Frozen", "unique": "Frozen Mouse" },
    { "id": 80, "name": "Gargoyle", "unique": "Gargoyle Mouse" },
    { "id": 81, "name": "Gate Guardian", "unique": "Gate Guardian Mouse" },
    { "id": 82, "name": "Ghost", "unique": "Ghost Mouse" },
    { "id": 83, "name": "Giant Snail", "unique": "Giant Snail Mouse" },
    { "id": 84, "name": "Gladiator", "unique": "Gladiator Mouse" },
    { "id": 85, "name": "Glitchpaw", "unique": "Glitchpaw Mouse" },
    { "id": 86, "name": "Goblin", "unique": "Goblin Mouse" },
    { "id": 87, "name": "Gold", "unique": "Gold Mouse" },
    { "id": 88, "name": "Golem", "unique": "Golem Mouse" },
    { "id": 89, "name": "Gorgon", "unique": "Gorgon Mouse" },
    { "id": 90, "name": "Grandfather", "unique": "Grandfather Mouse" },
    { "id": 91, "name": "Granite", "unique": "Granite Mouse" },
    { "id": 92, "name": "Grey", "unique": "Grey Mouse" },
    { "id": 93, "name": "Grunt", "unique": "Grunt Mouse" },
    { "id": 94, "name": "Guardian", "unique": "Guardian Mouse" },
    { "id": 95, "name": "Guqin Player", "unique": "Guqin Player Mouse" },
    { "id": 96, "name": "Hapless", "unique": "Hapless Mouse" },
    { "id": 97, "name": "Harpy", "unique": "Harpy Mouse" },
    { "id": 98, "name": "Healer", "unique": "Healer Mouse" },
    { "id": 99, "name": "Hollowhead", "unique": "Hollowhead Mouse" },
    { "id": 100, "name": "Hope" },
    { "id": 101, "name": "Hydra", "unique": "Hydra Mouse" },
    { "id": 102, "name": "Ignis", "unique": "Ignis Mouse" },
    { "id": 103, "name": "Impersonator", "unique": "Impersonator Mouse" },
    { "id": 104, "name": "Industrious Digger", "unique": "Industrious Digger Mouse" },
    { "id": 105, "name": "Itty-Bitty Burroughs", "unique": "Itty-Bitty Burroughs Mouse" },
    { "id": 106, "name": "Rockstar", "unique": "Rockstar Mouse" },
    { "id": 107, "name": "Jurassic", "unique": "Jurassic Mouse" },
    { "id": 108, "name": "Keeper", "unique": "Keeper Mouse" },
    { "id": 109, "name": "Keeper's Assistant", "unique": "Keeper" },
    { "id": 110, "name": "Knight", "unique": "Knight Mouse" },
    { "id": 111, "name": "Kung Fu", "unique": "Kung Fu Mouse" },
    { "id": 112, "name": "Lambent Crystal", "unique": "Lambent Crystal Mouse" },
    { "id": 113, "name": "Leprechaun", "catches": 0 },
    { "id": 114, "name": "Leviathan", "unique": "Leviathan Mouse" },
    { "id": 115, "name": "Lich", "unique": "Lich Mouse" },
    { "id": 116, "name": "Lockpick", "unique": "Lockpick Mouse" },
    { "id": 117, "name": "Longtail", "unique": "Longtail Mouse" },
    { "id": 118, "name": "Lycan", "unique": "Lycan Mouse" },
    { "id": 119, "name": "Magma Carrier", "unique": "Magma Carrier Mouse" },
    { "id": 120, "name": "Master Burglar", "unique": "Master Burglar Mouse" },
    { "id": 121, "name": "Master of the Cheese Belt", "unique": "Master of the Cheese Belt Mouse" },
    { "id": 122, "name": "Master of the Cheese Claw", "unique": "Master of the Cheese Claw Mouse" },
    { "id": 123, "name": "Master of the Cheese Fang", "unique": "Master of the Cheese Fang Mouse" },
    { "id": 124, "name": "Master of the Dojo", "unique": "Master of the Dojo Mouse" },
    { "id": 125, "name": "Mermouse", "unique": "Mermouse" },
    { "id": 126, "name": "Miner", "unique": "Miner Mouse" },
    { "id": 127, "name": "Mintaka", "unique": "Mintaka Mouse" },
    { "id": 128, "name": "Mobster" },
    { "id": 129, "name": "Mole", "unique": "Mole Mouse" },
    { "id": 130, "name": "Monk", "unique": "Monk Mouse" },
    { "id": 131, "name": "Monster", "unique": "Monster Mouse" },
    { "id": 132, "name": "Moosker", "unique": "Moosker Mouse" },
    { "id": 133, "name": "Mummy", "unique": "Mummy Mouse" },
    { "id": 134, "name": "Mutated Grey", "unique": "Mutated Grey Mouse" },
    { "id": 135, "name": "Mutated White", "unique": "Mutated White Mouse" },
    { "id": 136, "name": "Mystic", "unique": "Mystic Mouse" },
    { "id": 137, "name": "Narrator", "unique": "Narrator Mouse" },
    { "id": 138, "name": "Necromancer", "unique": "Necromancer Mouse" },
    { "id": 139, "name": "Nerg Chieftain", "unique": "Nerg Chieftain Mouse" },
    { "id": 140, "name": "Nerg Lich", "unique": "Nerg Lich Mouse" },
    { "id": 141, "name": "New Year's", "unique": "New Year" },
    { "id": 142, "name": "Nibbler", "unique": "Nibbler Mouse" },
    { "id": 143, "name": "Ninja", "unique": "Ninja Mouse" },
    { "id": 144, "name": "Nomad", "unique": "Nomad Mouse" },
    { "id": 145, "name": "Nugget", "unique": "Nugget Mouse" },
    { "id": 146, "name": "Nutcracker", "unique": "Nutcracker Mouse" },
    { "id": 147, "name": "Ooze", "unique": "Ooze Mouse" },
    { "id": 148, "name": "Ornament", "unique": "Ornament Mouse" },
    { "id": 149, "name": "Pack", "unique": "Pack Mouse" },
    { "id": 150, "name": "Page", "unique": "Page Mouse" },
    { "id": 151, "name": "Paladin", "unique": "Paladin Mouse" },
    { "id": 152, "name": "Pathfinder", "unique": "Pathfinder Mouse" },
    { "id": 153, "name": "Phalanx", "unique": "Phalanx Mouse" },
    { "id": 154, "name": "Swarm of Pygmy Mice", "unique": "Swarm of Pygmy Mice" },
    { "id": 155, "name": "Pinchy", "unique": "Pinchy Mouse" },
    { "id": 156, "name": "Pirate", "unique": "Pirate Mouse" },
    { "id": 157, "name": "Present", "unique": "Present Mouse" },
    { "id": 158, "name": "Primal", "unique": "Primal Mouse" },
    { "id": 159, "name": "Protector", "unique": "Protector Mouse" },
    { "id": 160, "name": "Puppet Master", "unique": "Puppet Master Mouse" },
    { "id": 161, "name": "Ravenous Zombie", "unique": "Ravenous Zombie Mouse" },
    { "id": 162, "name": "Reaper", "unique": "Reaper Mouse" },
    { "id": 163, "name": "Red Envelope", "unique": "Red Envelope Mouse" },
    { "id": 164, "name": "Renegade", "unique": "Renegade Mouse" },
    { "id": 165, "name": "Riptide", "unique": "Riptide Mouse" },
    { "id": 166, "name": "Rock Muncher", "unique": "Rock Muncher Mouse" },
    { "id": 167, "name": "Rogue", "unique": "Rogue Mouse" },
    { "id": 168, "name": "Romeno", "unique": "Romeno Mouse" },
    { "id": 169, "name": "Romeo", "unique": "Romeo Mouse" },
    { "id": 170, "name": "Sacred Shrine", "unique": "Sacred Shrine Mouse" },
    { "id": 171, "name": "Salt Water Snapper", "unique": "Salt Water Snapper Mouse" },
    { "id": 172, "name": "Samurai", "unique": "Samurai Mouse" },
    { "id": 173, "name": "Scavenger", "unique": "Scavenger Mouse" },
    { "id": 174, "name": "Scout", "unique": "Scout Mouse" },
    { "id": 175, "name": "Scrooge", "unique": "Scrooge Mouse" },
    { "id": 176, "name": "Seer", "unique": "Seer Mouse" },
    { "id": 177, "name": "Shaman", "unique": "Shaman Mouse" },
    { "id": 178, "name": "Shelder" },
    { "id": 179, "name": "Shipwrecked", "unique": "Shipwrecked Mouse" },
    { "id": 180, "name": "Silth", "unique": "Silth Mouse" },
    { "id": 181, "name": "Siren", "unique": "Siren Mouse" },
    { "id": 182, "name": "Skeleton", "unique": "Skeleton Mouse" },
    { "id": 183, "name": "Slayer", "unique": "Slayer Mouse" },
    { "id": 184, "name": "Sock Puppet Ghost", "unique": "Sock Puppet Ghost Mouse" },
    { "id": 185, "name": "Soothsayer", "unique": "Soothsayer Mouse" },
    { "id": 186, "name": "Sorcerer", "unique": "Sorcerer Mouse" },
    { "id": 187, "name": "Spectre", "unique": "Spectre Mouse" },
    { "id": 188, "name": "Spellbinder", "unique": "Spellbinder Mouse" },
    { "id": 189, "name": "Spider", "unique": "Spider Mouse" },
    { "id": 190, "name": "Squeaken", "unique": "Squeaken Mouse" },
    { "id": 191, "name": "Stealth", "unique": "Stealth Mouse" },
    { "id": 192, "name": "Steel", "unique": "Steel Mouse" },
    { "id": 193, "name": "Stocking", "unique": "Stocking Mouse" },
    { "id": 194, "name": "Stone Cutter", "unique": "Stone Cutter Mouse" },
    { "id": 195, "name": "Stonework Warrior", "unique": "Stonework Warrior Mouse" },
    { "id": 196, "name": "Student of the Cheese Belt", "unique": "Student of the Cheese Belt Mouse" },
    { "id": 197, "name": "Student of the Cheese Claw", "unique": "Student of the Cheese Claw Mouse" },
    { "id": 198, "name": "Student of the Cheese Fang", "unique": "Student of the Cheese Fang Mouse" },
    { "id": 199, "name": "Subterranean", "unique": "Subterranean Mouse" },
    { "id": 200, "name": "Swabbie", "unique": "Swabbie Mouse" },
    { "id": 201, "name": "Sylvan", "unique": "Sylvan Mouse" },
    { "id": 202, "name": "Taleweaver", "unique": "Taleweaver Mouse" },
    { "id": 203, "name": "Terra", "unique": "Terra Mouse" },
    { "id": 204, "name": "Terrible Twos", "unique": "Terrible Twos Mouse" },
    { "id": 205, "name": "Terror Knight", "unique": "Terror Knight Mouse" },
    { "id": 206, "name": "Tiger", "unique": "Tiger Mouse" },
    { "id": 207, "name": "Toy", "unique": "Toy Mouse" },
    { "id": 208, "name": "Toy Sylvan", "unique": "Toy Sylvan Mouse" },
    { "id": 209, "name": "Trailblazer", "unique": "Trailblazer Mouse" },
    { "id": 210, "name": "Treant", "unique": "Treant Mouse" },
    { "id": 211, "name": "Troll", "unique": "Troll Mouse" },
    { "id": 212, "name": "Twisted Fiend", "unique": "Twisted Fiend Mouse" },
    { "id": 213, "name": "Vampire", "unique": "Vampire Mouse" },
    { "id": 214, "name": "Vanquisher", "unique": "Vanquisher Mouse" },
    { "id": 215, "name": "Water Nymph", "unique": "Water Nymph Mouse" },
    { "id": 216, "name": "Whelpling", "unique": "Whelpling Mouse" },
    { "id": 217, "name": "White", "unique": "White Mouse" },
    { "id": 218, "name": "White Mage", "unique": "White Mage Mouse" },
    { "id": 219, "name": "Wicked Witch of Whisker Woods", "unique": "Wicked Witch of Whisker Woods Mouse" },
    { "id": 220, "name": "Wiggler", "unique": "Wiggler Mouse" },
    { "id": 221, "name": "Wight", "unique": "Wight Mouse" },
    { "id": 222, "name": "Wordsmith", "unique": "Wordsmith Mouse" },
    { "id": 223, "name": "Worker", "unique": "Worker Mouse" },
    { "id": 224, "name": "Wound Up White", "unique": "Wound Up White Mouse" },
    { "id": 225, "name": "Zephyr", "unique": "Zephyr Mouse" },
    { "id": 226, "name": "Zombie", "unique": "Zombie Mouse" },
    { "id": 227, "name": "Cowardly", "unique": "Cowardly Mouse" },
    { "id": 228, "name": "Farmhand" },
    { "id": 229, "name": "Speedy", "unique": "Speedy Mouse" },
    { "id": 230, "name": "Field", "unique": "Field Mouse" },
    { "id": 231, "name": "Fog" },
    { "id": 232, "name": "Lightning Rod", "unique": "Lightning Rod Mouse" },
    { "id": 233, "name": "Magic", "unique": "Magic Mouse" },
    { "id": 234, "name": "Pebble" },
    { "id": 235, "name": "Pugilist", "unique": "Pugilist Mouse" },
    { "id": 236, "name": "Scruffy", "unique": "Scruffy Mouse" },
    { "id": 237, "name": "Silvertail", "unique": "Silvertail Mouse" },
    { "id": 238, "name": "Spud", "unique": "Spud Mouse" },
    { "id": 239, "name": "Tiny", "unique": "Tiny Mouse" },
    { "id": 240, "name": "Cherry", "unique": "Cherry Mouse" },
    { "id": 241, "name": "Spotted", "unique": "Spotted Mouse" },
    { "id": 242, "name": "Derpicorn", "unique": "Derpicorn Mouse" },
    { "id": 243, "name": "Fall Familiar", "unique": "Fall Familiar Mouse" },
    { "id": 244, "name": "Firebreather", "unique": "Firebreather Mouse" },
    { "id": 245, "name": "Firefly", "unique": "Firefly Mouse" },
    { "id": 246, "name": "Frostbite", "unique": "Frostbite Mouse" },
    { "id": 247, "name": "Harvest Harrier", "unique": "Harvest Harrier Mouse" },
    { "id": 248, "name": "Harvester", "unique": "Harvester Mouse" },
    { "id": 249, "name": "Hot Head", "unique": "Hot Head Mouse" },
    { "id": 250, "name": "Hydrophobe", "unique": "Hydrophobe Mouse" },
    { "id": 251, "name": "Icicle", "unique": "Icicle Mouse" },
    { "id": 252, "name": "Monarch", "unique": "Monarch Mouse" },
    { "id": 253, "name": "Mystic Bishop", "unique": "Mystic Bishop Mouse" },
    { "id": 254, "name": "Mystic King", "unique": "Mystic King Mouse" },
    { "id": 255, "name": "Mystic Knight", "unique": "Mystic Knight Mouse" },
    { "id": 256, "name": "Mystic Pawn", "unique": "Mystic Pawn Mouse" },
    { "id": 257, "name": "Mystic Queen", "unique": "Mystic Queen Mouse" },
    { "id": 258, "name": "Mystic Rook", "unique": "Mystic Rook Mouse" },
    { "id": 259, "name": "Over-Prepared", "unique": "Over-Prepared Mouse" },
    { "id": 260, "name": "Penguin", "unique": "Penguin Mouse" },
    { "id": 261, "name": "Puddlemancer", "unique": "Puddlemancer Mouse" },
    { "id": 262, "name": "Pumpkin Head", "unique": "Pumpkin Head Mouse" },
    { "id": 263, "name": "Scarecrow", "unique": "Scarecrow Mouse" },
    { "id": 264, "name": "Spring Familiar" },
    { "id": 265, "name": "Stinger", "unique": "Stinger Mouse" },
    { "id": 266, "name": "Summer Mage", "unique": "Summer Mage Mouse" },
    { "id": 267, "name": "Tanglefoot", "unique": "Tanglefoot Mouse" },
    { "id": 268, "name": "Technic Bishop", "unique": "Technic Bishop Mouse" },
    { "id": 269, "name": "Technic King", "unique": "Technic King Mouse" },
    { "id": 270, "name": "Technic Knight", "unique": "Technic Knight Mouse" },
    { "id": 271, "name": "Technic Pawn", "unique": "Technic Pawn Mouse" },
    { "id": 272, "name": "Technic Queen", "unique": "Technic Queen Mouse" },
    { "id": 273, "name": "Technic Rook", "unique": "Technic Rook Mouse" },
    { "id": 274, "name": "Vinetail", "unique": "Vinetail Mouse" },
    { "id": 275, "name": "Whirleygig", "unique": "Whirleygig Mouse" },
    { "id": 276, "name": "Winter Mage", "unique": "Winter Mage Mouse" },
    { "id": 277, "name": "Bruticle", "unique": "Bruticle Mouse" },
    { "id": 278, "name": "Chess Master", "unique": "Chess Master" },
    { "id": 279, "name": "Realm Ripper", "unique": "Realm Ripper" },
    { "id": 280, "name": "Tidal Fisher", "unique": "Tidal Fisher Mouse" },
    { "id": 281, "name": "Gourdborg", "unique": "Gourdborg" },
    { "id": 282, "name": "Treat", "unique": "Treat Mouse" },
    { "id": 283, "name": "Trick", "unique": "Trick Mouse" },
    { "id": 284, "name": "Zombot Unipire", "unique": "Zombot Unipire Mouse" },
    { "id": 285, "name": "High Roller", "catches": 0 },
    { "id": 286, "name": "Snooty" },
    { "id": 287, "name": "Treasurer" },
    { "id": 288, "name": "Missile Toe", "unique": "Missile Toe Mouse" },
    { "id": 289, "name": "Slay Ride", "unique": "Slay Ride Mouse" },
    { "id": 290, "name": "Snow Fort", "unique": "Snow Fort Mouse" },
    { "id": 291, "name": "Squeaker Claws", "unique": "Squeaker Claws" },
    { "id": 292, "name": "Wreath Thief", "unique": "Wreath Thief Mouse" },
    { "id": 293, "name": "Mouse of Winter Future", "unique": "Mouse of Winter Future" },
    { "id": 294, "name": "Mouse of Winter Past", "unique": "Mouse of Winter Past" },
    { "id": 295, "name": "Mouse of Winter Present", "unique": "Mouse of Winter Present" },
    { "id": 296, "name": "Costumed Rabbit", "unique": "Costumed Rabbit Mouse" },
    { "id": 297, "name": "Juliyes", "unique": "Juliyes Mouse" },
    { "id": 298, "name": "Buckethead", "unique": "Buckethead Mouse" },
    { "id": 299, "name": "Pintail", "unique": "Pintail Mouse" },
    { "id": 300, "name": "Sleepwalker", "unique": "Sleepwalker Mouse" },
    { "id": 301, "name": "Flame Archer", "unique": "Flame Archer Mouse" },
    { "id": 302, "name": "Crimson Ranger", "unique": "Crimson Ranger Mouse" },
    { "id": 303, "name": "Desert Archer", "unique": "Desert Archer Mouse" },
    { "id": 304, "name": "Flame Ordnance", "unique": "Flame Ordnance Mouse" },
    { "id": 305, "name": "Gargantuamouse", "unique": "Gargantuamouse" },
    { "id": 306, "name": "Warmonger", "unique": "Warmonger Mouse" },
    { "id": 307, "name": "Sand Cavalry", "unique": "Sand Cavalry Mouse" },
    { "id": 308, "name": "Sandwing Cavalry", "unique": "Sandwing Cavalry Mouse" },
    { "id": 309, "name": "Theurgy Warden", "unique": "Theurgy Warden Mouse" },
    { "id": 310, "name": "Crimson Commander", "unique": "Crimson Commander Mouse" },
    { "id": 311, "name": "Inferno Mage", "unique": "Inferno Mage Mouse" },
    { "id": 312, "name": "Magmarage", "unique": "Magmarage Mouse" },
    { "id": 313, "name": "Sentinel", "unique": "Sentinel Mouse" },
    { "id": 314, "name": "Crimson Watch", "unique": "Crimson Watch Mouse" },
    { "id": 315, "name": "Vanguard", "unique": "Vanguard Mouse" },
    { "id": 316, "name": "Caravan Guard", "unique": "Caravan Guard Mouse" },
    { "id": 317, "name": "Flame Warrior", "unique": "Flame Warrior Mouse" },
    { "id": 318, "name": "Crimson Titan", "unique": "Crimson Titan Mouse" },
    { "id": 319, "name": "Desert Soldier", "unique": "Desert Soldier Mouse" },
    { "id": 320, "name": "Coco Commander", "unique": "Coco Commander Mouse" },
    { "id": 321, "name": "Egg Painter", "unique": "Egg Painter Mouse" },
    { "id": 322, "name": "Eggsplosive Scientist", "unique": "Eggsplosive Scientist Mouse" },
    { "id": 323, "name": "Hare Razer", "unique": "Hare Razer Mouse" },
    { "id": 324, "name": "Blacksmith", "unique": "Blacksmith Mouse" },
    { "id": 325, "name": "Lumberjack", "unique": "Lumberjack Mouse" },
    { "id": 326, "name": "Desert Nomad", "unique": "Desert Nomad Mouse" },
    { "id": 327, "name": "Desert Architect", "unique": "Desert Architect Mouse" },
    { "id": 328, "name": "Falling Carpet", "unique": "Falling Carpet Mouse" },
    { "id": 329, "name": "Glass Blower", "unique": "Glass Blower Mouse" },
    { "id": 330, "name": "Limestone Miner", "unique": "Limestone Miner Mouse" },
    { "id": 331, "name": "Mage Weaver", "unique": "Mage Weaver Mouse" },
    { "id": 332, "name": "Market Guard", "unique": "Market Guard Mouse" },
    { "id": 333, "name": "Market Thief", "unique": "Market Thief Mouse" },
    { "id": 334, "name": "Pie Thief", "unique": "Pie Thief Mouse" },
    { "id": 335, "name": "Snake Charmer", "unique": "Snake Charmer Mouse" },
    { "id": 336, "name": "Spice Merchant", "unique": "Spice Merchant Mouse" },
    { "id": 337, "name": "Grave Robber", "unique": "Grave Robber Mouse" },
    { "id": 338, "name": "Aether" },
    { "id": 339, "name": "Bookborn", "unique": "Bookborn Mouse" },
    { "id": 340, "name": "Effervescent", "unique": "Effervescent Mouse" },
    { "id": 341, "name": "Explorator", "unique": "Explorator Mouse" },
    { "id": 342, "name": "Flutterby", "unique": "Flutterby Mouse" },
    { "id": 343, "name": "Infiltrator", "unique": "Infiltrator Mouse" },
    { "id": 344, "name": "Zurreal the Eternal" },
    { "id": 345, "name": "Pocketwatch", "unique": "Pocketwatch Mouse" },
    { "id": 346, "name": "Scribe", "unique": "Scribe Mouse" },
    { "id": 347, "name": "Steam Grip", "unique": "Steam Grip Mouse" },
    { "id": 348, "name": "Tome Sprite", "unique": "Tome Sprite Mouse" },
    { "id": 349, "name": "Walker", "unique": "Walker Mouse" },
    { "id": 350, "name": "Crown Collector", "unique": "Crown Collector Mouse" },
    { "id": 351, "name": "Mousevina von Vermin", "unique": "Mousevina von Vermin" },
    { "id": 352, "name": "Cobweb", "unique": "Cobweb Mouse" },
    { "id": 353, "name": "Pumpkin Hoarder", "unique": "Pumpkin Hoarder Mouse" },
    { "id": 354, "name": "Destructoy", "unique": "Destructoy Mouse" },
    { "id": 355, "name": "Snowflake", "unique": "Snowflake Mouse" },
    { "id": 356, "name": "Snow Scavenger", "unique": "Snow Scavenger" },
    { "id": 357, "name": "Toy Tinkerer", "unique": "Toy Tinkerer Mouse" },
    { "id": 358, "name": "Mad Elf", "unique": "Mad Elf Mouse" },
    { "id": 359, "name": "Party Head", "unique": "Party Head Mouse" },
    { "id": 360, "name": "Calligraphy", "unique": "Calligraphy Mouse" },
    { "id": 361, "name": "Costumed Dragon", "unique": "Costumed Dragon Mouse" },
    { "id": 362, "name": "Forever Alone", "unique": "Forever Alone Mouse" },
    { "id": 363, "name": "Pygmy Wrangler", "unique": "Pygmy Wrangler Mouse" },
    { "id": 364, "name": "Dinosuit", "unique": "Dinosuit Mouse" },
    { "id": 365, "name": "Eggscavator", "unique": "Eggscavator Mouse" },
    { "id": 366, "name": "Sinister Egg Painter", "unique": "Sinister Egg Painter" },
    { "id": 367, "name": "Incompetent Ice Climber", "unique": "Incompetent Ice Climber Mouse" },
    { "id": 368, "name": "Polar Bear", "unique": "Polar Bear Mouse" },
    { "id": 369, "name": "Snow Soldier", "unique": "Snow Soldier Mouse" },
    { "id": 370, "name": "Wolfskie", "unique": "Wolfskie Mouse" },
    { "id": 371, "name": "Chipper", "unique": "Chipper Mouse" },
    { "id": 372, "name": "Snow Bowler", "unique": "Snow Bowler Mouse" },
    { "id": 373, "name": "Snow Slinger", "unique": "Snow Slinger Mouse" },
    { "id": 374, "name": "Icebreaker", "unique": "Icebreaker Mouse" },
    { "id": 375, "name": "Saboteur", "unique": "Saboteur Mouse" },
    { "id": 376, "name": "Snow Sniper", "unique": "Snow Sniper Mouse" },
    { "id": 377, "name": "Yeti", "unique": "Yeti Mouse" },
    { "id": 378, "name": "Living Ice", "unique": "Living Ice Mouse" },
    { "id": 379, "name": "General Drheller" },
    { "id": 380, "name": "Frostlance Guard", "unique": "Frostlance Guard" },
    { "id": 381, "name": "Frostwing Commander", "unique": "Frostwing Commander" },
    { "id": 382, "name": "Heavy Blaster", "unique": "Heavy Blaster Mouse" },
    { "id": 383, "name": "Iceblade", "unique": "Iceblade Mouse" },
    { "id": 384, "name": "Iceblock", "unique": "Iceblock Mouse" },
    { "id": 385, "name": "Icewing", "unique": "Icewing" },
    { "id": 386, "name": "Lady Coldsnap", "unique": "Lady Coldsnap" },
    { "id": 387, "name": "Lord Splodington", "unique": "Lord Splodington" },
    { "id": 388, "name": "Mammoth", "unique": "Mammoth Mouse" },
    { "id": 389, "name": "Princess Fist", "unique": "Princess Fist" },
    { "id": 390, "name": "Snowblind", "unique": "Snowblind Mouse" },
    { "id": 391, "name": "Stickybomber", "unique": "Stickybomber Mouse" },
    { "id": 392, "name": "Water Wielder", "unique": "Water Wielder Mouse" },
    { "id": 393, "name": "Living Salt", "unique": "Living Salt Mouse" },
    { "id": 394, "name": "Deep" },
    { "id": 395, "name": "Lucky", "unique": "Lucky Mouse" },
    { "id": 396, "name": "Chrono", "unique": "Chrono Mouse" },
    { "id": 397, "name": "Hurdle", "unique": "Hurdle Mouse" },
    { "id": 398, "name": "Extreme Everysports", "unique": "Extreme Everysports Mouse" },
    { "id": 399, "name": "Trampoline", "unique": "Trampoline Mouse" },
    { "id": 400, "name": "Goldleaf" },
    { "id": 401, "name": "Relic Hunter", "unique": "Relic Hunter Mouse" },
    { "id": 402, "name": "Wild Chainsaw", "unique": "Wild Chainsaw Mouse" },
    { "id": 403, "name": "Swamp Thang", "unique": "Swamp Thang Mouse" },
    { "id": 404, "name": "Spirit Light", "unique": "Spirit Light Mouse" },
    { "id": 405, "name": "Bark", "unique": "Bark Mouse" },
    { "id": 406, "name": "Barkshell", "unique": "Barkshell Mouse" },
    { "id": 407, "name": "Calalilly", "unique": "Calalilly Mouse" },
    { "id": 408, "name": "Camoflower", "unique": "Camoflower Mouse" },
    { "id": 409, "name": "Camofusion", "unique": "Camofusion Mouse" },
    { "id": 410, "name": "Carmine the Apothecary", "unique": "Carmine the Apothecary" },
    { "id": 411, "name": "Corrupt", "unique": "Corrupt Mouse" },
    { "id": 412, "name": "Cursed", "unique": "Cursed Mouse" },
    { "id": 413, "name": "Cursed Enchanter", "unique": "Cursed Enchanter Mouse" },
    { "id": 414, "name": "Cursed Engineer", "unique": "Cursed Engineer Mouse" },
    { "id": 415, "name": "Cursed Librarian", "unique": "Cursed Librarian Mouse" },
    { "id": 416, "name": "Cursed Thief", "unique": "Cursed Thief Mouse" },
    { "id": 417, "name": "Dehydrated", "unique": "Dehydrated Mouse" },
    { "id": 418, "name": "Dunehopper", "unique": "Dunehopper Mouse" },
    { "id": 419, "name": "Essence Collector", "unique": "Essence Collector Mouse" },
    { "id": 420, "name": "Essence Guardian", "unique": "Essence Guardian Mouse" },
    { "id": 421, "name": "Ethereal Enchanter", "unique": "Ethereal Enchanter Mouse" },
    { "id": 422, "name": "Ethereal Engineer", "unique": "Ethereal Engineer" },
    { "id": 423, "name": "Ethereal Librarian", "unique": "Ethereal Librarian" },
    { "id": 424, "name": "Ethereal Thief", "unique": "Ethereal Thief Mouse" },
    { "id": 425, "name": "Fungal Spore", "unique": "Fungal Spore Mouse" },
    { "id": 426, "name": "Grubling", "unique": "Grubling Mouse" },
    { "id": 427, "name": "Grubling Herder", "unique": "Grubling Herder Mouse" },
    { "id": 428, "name": "King Grub", "unique": "King Grub Mouse" },
    { "id": 429, "name": "Quesodillo", "unique": "Quesodillo Mouse" },
    { "id": 430, "name": "Sand Colossus", "unique": "Sand Colossus Mouse" },
    { "id": 431, "name": "Sand Pilgrim", "unique": "Sand Pilgrim" },
    { "id": 432, "name": "Sarcophamouse", "unique": "Sarcophamouse" },
    { "id": 433, "name": "Scarab", "unique": "Scarab Mouse" },
    { "id": 434, "name": "Serpentine", "unique": "Serpentine Mouse" },
    { "id": 435, "name": "Shroom", "unique": "Shroom Mouse" },
    { "id": 436, "name": "Spiky Devil", "unique": "Spiky Devil Mouse" },
    { "id": 437, "name": "Strawberry Hotcakes", "unique": "Strawberry Hotcakes Mouse" },
    { "id": 438, "name": "Thirsty", "unique": "Thirsty Mouse" },
    { "id": 439, "name": "Thistle", "unique": "Thistle Mouse" },
    { "id": 440, "name": "Thorn", "unique": "Thorn Mouse" },
    { "id": 441, "name": "Twisted Carmine", "unique": "Twisted Carmine" },
    { "id": 442, "name": "Twisted Hotcakes", "unique": "Twisted Hotcakes Mouse" },
    { "id": 443, "name": "Twisted Lilly", "unique": "Twisted Lilly Mouse" },
    { "id": 444, "name": "Confused Courier", "unique": "Confused Courier Mouse" },
    { "id": 445, "name": "Gingerbread", "unique": "Gingerbread Mouse" },
    { "id": 446, "name": "Greedy Al", "unique": "Greedy Al" },
    { "id": 447, "name": "Ribbon", "unique": "Ribbon Mouse" },
    { "id": 448, "name": "Ridiculous Sweater", "unique": "Ridiculous Sweater Mouse" },
    { "id": 449, "name": "Snowblower", "unique": "Snowblower Mouse" },
    { "id": 450, "name": "Snowglobe", "unique": "Snowglobe Mouse" },
    { "id": 451, "name": "Triple Lutz", "unique": "Triple Lutz Mouse" },
    { "id": 454, "name": "Shattered Carmine", "catches": 0 },
    { "id": 452, "name": "Dark Magi", "catches": 0 },
    { "id": 453, "name": "King Scarab", "catches": 0 },
    { "id": 455, "name": "Costumed Snake", "unique": "Costumed Snake Mouse" },
    { "id": 456, "name": "Totally Not Bitter", "unique": "Totally Not Bitter Mouse" },
    { "id": 457, "name": "Force Fighter Blue", "unique": "Force Fighter Blue" },
    { "id": 458, "name": "Force Fighter Green", "unique": "Force Fighter Green" },
    { "id": 459, "name": "Force Fighter Pink", "unique": "Force Fighter Pink" },
    { "id": 460, "name": "Force Fighter Red", "unique": "Force Fighter Red" },
    { "id": 461, "name": "Force Fighter Yellow", "unique": "Force Fighter Yellow" },
    { "id": 462, "name": "Super FighterBot MegaSupreme", "unique": "Super FighterBot MegaSupreme" },
    { "id": 463, "name": "Chocolate Overload", "unique": "Chocolate Overload Mouse" },
    { "id": 464, "name": "Egg Scrambler", "unique": "Egg Scrambler Mouse" },
    { "id": 465, "name": "Hardboiled", "unique": "Hardboiled Mouse" },
    { "id": 466, "name": "Bartender", "unique": "Bartender" },
    { "id": 467, "name": "Bounty Hunter", "unique": "Bounty Hunter" },
    { "id": 468, "name": "Cardshark", "unique": "Cardshark" },
    { "id": 469, "name": "Circuit Judge", "unique": "Circuit Judge" },
    { "id": 470, "name": "Coal Shoveler", "unique": "Coal Shoveller Mouse" },
    { "id": 471, "name": "Desperado", "unique": "Desperado" },
    { "id": 472, "name": "Farrier", "unique": "Farrier" },
    { "id": 473, "name": "Lasso Cowgirl", "unique": "Lasso Cowgirl" },
    { "id": 474, "name": "Outlaw", "unique": "Outlaw" },
    { "id": 475, "name": "Parlour Player", "unique": "Parlour Player" },
    { "id": 476, "name": "Prospector", "unique": "Prospector" },
    { "id": 477, "name": "Pyrite", "unique": "Pyrite" },
    { "id": 478, "name": "Ruffian", "unique": "Ruffian" },
    { "id": 479, "name": "Saloon Gal", "unique": "Saloon Gal" },
    { "id": 480, "name": "Shopkeeper", "unique": "Shopkeeper" },
    { "id": 481, "name": "Stagecoach Driver", "unique": "Stagecoach Driver" },
    { "id": 482, "name": "Stuffy Banker", "unique": "Stuffy Banker" },
    { "id": 483, "name": "Tonic Salesman", "unique": "Tonic Salesman" },
    { "id": 484, "name": "Tumbleweed", "unique": "Tumbleweed" },
    { "id": 485, "name": "Undertaker", "unique": "Undertaker" },
    { "id": 486, "name": "Upper Class Lady" },
    { "id": 487, "name": "Angry Train Staff" },
    { "id": 488, "name": "Automorat" },
    { "id": 489, "name": "Black Powder Thief" },
    { "id": 490, "name": "Cannonball" },
    { "id": 491, "name": "Crate Camo" },
    { "id": 492, "name": "Cute Crate Carrier" },
    { "id": 493, "name": "Fuel" },
    { "id": 495, "name": "Hookshot" },
    { "id": 496, "name": "Magmatic Crystal Thief" },
    { "id": 497, "name": "Magmatic Golem" },
    { "id": 498, "name": "Mouse With No Name" },
    { "id": 499, "name": "Mysterious Traveller" },
    { "id": 500, "name": "Passenger" },
    { "id": 501, "name": "Photographer" },
    { "id": 502, "name": "Sharpshooter" },
    { "id": 503, "name": "Steel Horse Rider" },
    { "id": 504, "name": "Stoutgear" },
    { "id": 505, "name": "Stowaway" },
    { "id": 506, "name": "Supply Hoarder" },
    { "id": 507, "name": "Dangerous Duo" },
    { "id": 508, "name": "Train Conductor" },
    { "id": 509, "name": "Train Engineer" },
    { "id": 510, "name": "Travelling Barber" },
    { "id": 511, "name": "Warehouse Manager" },
    { "id": 512, "name": "Gluttonous Zombie" },
    { "id": 513, "name": "Titanic Brain-Taker" },
    { "id": 514, "name": "Mutated Brown" },
    { "id": 515, "name": "Sugar Rush" },
    { "id": 516, "name": "S.N.O.W. Golem" },
    { "id": 517, "name": "Snow Boulder" },
    { "id": 518, "name": "Snow Sorceress" },
    { "id": 519, "name": "Reinbo" },
    { "id": 520, "name": "Snowball Hoarder" },
    { "id": 521, "name": "Mutated Behemoth" },
    { "id": 522, "name": "Biohazard" },
    { "id": 523, "name": "Bog Beast" },
    { "id": 524, "name": "Gelatinous Octahedron" },
    { "id": 525, "name": "Hazmat" },
    { "id": 526, "name": "Lab Technician" },
    { "id": 527, "name": "The Menace" },
    { "id": 528, "name": "Monster Tail" },
    { "id": 529, "name": "Mutant Mongrel" },
    { "id": 530, "name": "Mutant Ninja" },
    { "id": 531, "name": "Mutated Siblings" },
    { "id": 532, "name": "Outbreak Assassin" },
    { "id": 533, "name": "Plague Hag" },
    { "id": 534, "name": "Scrap Metal Monster" },
    { "id": 535, "name": "Slimefist" },
    { "id": 536, "name": "Sludge" },
    { "id": 537, "name": "Sludge Soaker" },
    { "id": 538, "name": "Sludge Swimmer" },
    { "id": 539, "name": "Spore" },
    { "id": 540, "name": "Swamp Runner" },
    { "id": 541, "name": "Telekinetic Mutant" },
    { "id": 542, "name": "Tentacle" },
    { "id": 543, "name": "Toxic Warrior" },
    { "id": 544, "name": "Costumed Horse" },
    { "id": 545, "name": "Lovely Sports" },
    { "id": 546, "name": "Winter Games" },
    { "id": 547, "name": "M400" },
    { "id": 548, "name": "Breakdancer" },
    { "id": 549, "name": "El Flamenco" },
    { "id": 550, "name": "Dance Party" },
    { "id": 551, "name": "Para Para Dancer" },
    { "id": 552, "name": "Moussile" },
    { "id": 553, "name": "Cyborg" },
    { "id": 554, "name": "Riftweaver" },
    { "id": 555, "name": "Agitated Gentle Giant" },
    { "id": 556, "name": "Raw Diamond" },
    { "id": 557, "name": "Rift Guardian" },
    { "id": 558, "name": "Goliath Field" },
    { "id": 559, "name": "Dream Drifter" },
    { "id": 560, "name": "Wealth" },
    { "id": 561, "name": "Shard Centurion" },
    { "id": 562, "name": "Greyrun" },
    { "id": 563, "name": "Excitable Electric" },
    { "id": 564, "name": "Mighty Mole" },
    { "id": 565, "name": "Supernatural" },
    { "id": 566, "name": "Spiritual Steel" },
    { "id": 567, "name": "Micro" },
    { "id": 568, "name": "Brawny" },
    { "id": 569, "name": "Carefree Cook" },
    { "id": 570, "name": "Onion Chopper" },
    { "id": 571, "name": "Pan Slammer" },
    { "id": 572, "name": "Ancient of the Deep" },
    { "id": 573, "name": "Angelfish" },
    { "id": 574, "name": "Angler" },
    { "id": 575, "name": "Barnacle Beautician" },
    { "id": 576, "name": "Barracuda" },
    { "id": 577, "name": "Betta" },
    { "id": 578, "name": "Bottom Feeder" },
    { "id": 579, "name": "Carnivore" },
    { "id": 580, "name": "City Noble" },
    { "id": 581, "name": "City Worker" },
    { "id": 582, "name": "Clownfish" },
    { "id": 583, "name": "Clumsy Carrier" },
    { "id": 584, "name": "Coral" },
    { "id": 585, "name": "Coral Cuddler" },
    { "id": 586, "name": "Coral Dragon" },
    { "id": 587, "name": "Coral Gardener" },
    { "id": 588, "name": "Coral Guard" },
    { "id": 589, "name": "Coral Harvester" },
    { "id": 590, "name": "Coral Queen" },
    { "id": 591, "name": "Crabolia" },
    { "id": 592, "name": "Cuttle" },
    { "id": 593, "name": "Deep Sea Diver" },
    { "id": 594, "name": "Deranged Deckhand" },
    { "id": 595, "name": "Derpshark" },
    { "id": 596, "name": "Dread Pirate Mousert" },
    { "id": 597, "name": "Eel" },
    { "id": 598, "name": "Elite Guardian" },
    { "id": 599, "name": "Enginseer" },
    { "id": 600, "name": "Guppy" },
    { "id": 601, "name": "Hydrologist" },
    { "id": 602, "name": "Jellyfish" },
    { "id": 603, "name": "Koimaid" },
    { "id": 604, "name": "Manatee" },
    { "id": 605, "name": "Mermousette" },
    { "id": 606, "name": "Mershark" },
    { "id": 607, "name": "Mlounder Flounder" },
    { "id": 608, "name": "Octomermaid" },
    { "id": 609, "name": "Old One" },
    { "id": 610, "name": "Oxygen Baron" },
    { "id": 611, "name": "Pearl" },
    { "id": 612, "name": "Pearl Diver" },
    { "id": 613, "name": "Pirate Anchor" },
    { "id": 614, "name": "Puffer" },
    { "id": 615, "name": "Saltwater Axolotl" },
    { "id": 616, "name": "Sand Dollar Diver" },
    { "id": 617, "name": "Sand Dollar Queen" },
    { "id": 618, "name": "School of Mish" },
    { "id": 619, "name": "Seadragon" },
    { "id": 620, "name": "Serpent Monster" },
    { "id": 621, "name": "Spear Fisher" },
    { "id": 622, "name": "Stingray" },
    { "id": 623, "name": "Sunken Banshee" },
    { "id": 624, "name": "Sunken Citizen" },
    { "id": 625, "name": "Swashblade" },
    { "id": 626, "name": "Tadpole" },
    { "id": 627, "name": "Treasure Hoarder" },
    { "id": 628, "name": "Treasure Keeper" },
    { "id": 629, "name": "Tritus" },
    { "id": 630, "name": "Turret Guard" },
    { "id": 631, "name": "Urchin King" },
    { "id": 632, "name": "Captain Croissant" },
    { "id": 633, "name": "Amplified Brown" },
    { "id": 634, "name": "Amplified Grey" },
    { "id": 635, "name": "Amplified White" },
    { "id": 636, "name": "Assassin Beast" },
    { "id": 637, "name": "Automated Sentry" },
    { "id": 638, "name": "Big Bad Behemoth Burroughs" },
    { "id": 639, "name": "Rift Bio Engineer" },
    { "id": 640, "name": "Boulder Biter" },
    { "id": 641, "name": "Clump" },
    { "id": 642, "name": "Count Vampire" },
    { "id": 643, "name": "Cyber Miner" },
    { "id": 644, "name": "Cybernetic Specialist" },
    { "id": 645, "name": "Doktor" },
    { "id": 646, "name": "Evil Scientist" },
    { "id": 647, "name": "Itty Bitty Rifty Burroughs" },
    { "id": 648, "name": "Lambent" },
    { "id": 649, "name": "Lycanoid" },
    { "id": 650, "name": "Master Exploder" },
    { "id": 651, "name": "Mecha Tail" },
    { "id": 652, "name": "The Menace of the Rift" },
    { "id": 653, "name": "Monstrous Abomination" },
    { "id": 654, "name": "Phase Zombie" },
    { "id": 655, "name": "Plutonium Tentacle" },
    { "id": 656, "name": "Pneumatic Dirt Displacement" },
    { "id": 657, "name": "Portable Generator" },
    { "id": 658, "name": "Prototype" },
    { "id": 659, "name": "Super Mega Mecha Ultra RoboGold" },
    { "id": 660, "name": "Rancid Bog Beast" },
    { "id": 661, "name": "Revenant" },
    { "id": 662, "name": "Rifterranian" },
    { "id": 663, "name": "Robat" },
    { "id": 664, "name": "Radioactive Ooze" },
    { "id": 665, "name": "Surgeon Bot" },
    { "id": 666, "name": "Tech Ravenous Zombie" },
    { "id": 667, "name": "Toxic Avenger" },
    { "id": 668, "name": "Toxikinetic" },
    { "id": 669, "name": "Zombot Unipire the Third" },
    { "id": 670, "name": "Candy Cat" },
    { "id": 671, "name": "Candy Goblin" },
    { "id": 672, "name": "Grey Recluse" },
    { "id": 673, "name": "Hollowed" },
    { "id": 674, "name": "Mousataur Priestess" },
    { "id": 675, "name": "Shortcut" },
    { "id": 676, "name": "Tricky Witch" },
    { "id": 677, "name": "Builder" },
    { "id": 678, "name": "Frigid Foreman" },
    { "id": 679, "name": "Glacia Ice Fist" },
    { "id": 680, "name": "Hoarder" },
    { "id": 681, "name": "Miser" },
    { "id": 682, "name": "Stuck Snowball" },
    { "id": 683, "name": "Tundra Huntress" },
    { "id": 684, "name": "Borean Commander" },
    { "id": 686, "name": "Red Coat Bear" },
    { "id": 687, "name": "Monstrous Black Widow" },
    { "id": 688, "name": "Centaur Ranger" },
    { "id": 689, "name": "Karmachameleon" },
    { "id": 690, "name": "Cherry Sprite" },
    { "id": 691, "name": "Naturalist" },
    { "id": 692, "name": "Cyclops Barbarian" },
    { "id": 693, "name": "Red-Eyed Watcher Owl" },
    { "id": 694, "name": "Treant Queen" },
    { "id": 695, "name": "Spirit of Balance" },
    { "id": 696, "name": "Spirit Fox" },
    { "id": 697, "name": "Fungal Frog" },
    { "id": 698, "name": "Crazed Goblin" },
    { "id": 699, "name": "Gilded Leaf" },
    { "id": 700, "name": "Winged Harpy" },
    { "id": 701, "name": "Tri-dra" },
    { "id": 702, "name": "Mossy Moosker" },
    { "id": 703, "name": "Nomadic Warrior" },
    { "id": 705, "name": "Medicine" },
    { "id": 706, "name": "Grizzled Silth" },
    { "id": 707, "name": "Bloomed Sylvan" },
    { "id": 708, "name": "Rift Tiger" },
    { "id": 709, "name": "Twisted Treant" },
    { "id": 710, "name": "Tree Troll" },
    { "id": 711, "name": "Water Sprite" },
    { "id": 712, "name": "Cranky Caterpillar" },
    { "id": 713, "name": "Gentleman Caller" },
    { "id": 714, "name": "Costumed Sheep" },
    { "id": 715, "name": "Cupcake Cutie" },
    { "id": 716, "name": "Cupcake Runner" },
    { "id": 717, "name": "Chocolate Gold Foil" },
    { "id": 718, "name": "Bitter Root" },
    { "id": 719, "name": "Cavern Crumbler" },
    { "id": 720, "name": "Crag Elder" },
    { "id": 721, "name": "Crystal Behemoth" },
    { "id": 722, "name": "Crystal Cave Worm" },
    { "id": 723, "name": "Crystal Controller" },
    { "id": 724, "name": "Crystal Golem" },
    { "id": 725, "name": "Crystal Lurker" },
    { "id": 726, "name": "Crystal Observer" },
    { "id": 727, "name": "Crystal Queen" },
    { "id": 728, "name": "Crystalback" },
    { "id": 729, "name": "Crystalline Slasher" },
    { "id": 730, "name": "Diamondhide" },
    { "id": 731, "name": "Dirt Thing" },
    { "id": 732, "name": "Floating Spore" },
    { "id": 733, "name": "Funglore" },
    { "id": 734, "name": "Gemorpher" },
    { "id": 735, "name": "Gemstone Worshipper" },
    { "id": 736, "name": "Huntereater" },
    { "id": 737, "name": "Lumahead" },
    { "id": 738, "name": "Mouldy Mole" },
    { "id": 739, "name": "Mush" },
    { "id": 740, "name": "Mushroom Sprite" },
    { "id": 741, "name": "Nightshade Masquerade" },
    { "id": 742, "name": "Quillback" },
    { "id": 743, "name": "Shattered Obsidian" },
    { "id": 744, "name": "Spiked Burrower" },
    { "id": 745, "name": "Splintered Stone Sentry" },
    { "id": 746, "name": "Spore Muncher" },
    { "id": 747, "name": "Sporeticus" },
    { "id": 748, "name": "Stalagmite" },
    { "id": 749, "name": "Stone Maiden" },
    { "id": 750, "name": "Ancient Scribe" },
    { "id": 751, "name": "Ash Golem" },
    { "id": 752, "name": "Automated Stone Sentry" },
    { "id": 753, "name": "Battle Cleric" },
    { "id": 754, "name": "Corridor Bruiser" },
    { "id": 755, "name": "Dark Templar" },
    { "id": 756, "name": "Decrepit Tentacle Terror" },
    { "id": 757, "name": "Drudge" },
    { "id": 758, "name": "Ethereal Guardian" },
    { "id": 759, "name": "Exo-Tech" },
    { "id": 760, "name": "Sir Fleekio" },
    { "id": 761, "name": "Fungal Technomorph" },
    { "id": 762, "name": "Hired Eidolon" },
    { "id": 763, "name": "Lost" },
    { "id": 764, "name": "Lost Legionnaire" },
    { "id": 765, "name": "Manaforge Smith" },
    { "id": 766, "name": "Paladin Weapon Master" },
    { "id": 767, "name": "Masked Pikeman" },
    { "id": 768, "name": "Matron of Machinery" },
    { "id": 769, "name": "Matron of Wealth" },
    { "id": 770, "name": "Mimic" },
    { "id": 771, "name": "Mind Tearer" },
    { "id": 772, "name": "Shadow Stalker" },
    { "id": 773, "name": "Molten Midas" },
    { "id": 774, "name": "Mush Monster" },
    { "id": 775, "name": "Mushroom Harvester" },
    { "id": 776, "name": "Mystic Guardian" },
    { "id": 777, "name": "Mystic Herald" },
    { "id": 778, "name": "Mystic Scholar" },
    { "id": 779, "name": "Nightshade Fungalmancer" },
    { "id": 780, "name": "Nightshade Nanny" },
    { "id": 781, "name": "Reanimated Carver" },
    { "id": 782, "name": "Retired Minotaur" },
    { "id": 783, "name": "RR-8" },
    { "id": 784, "name": "Sanguinarian" },
    { "id": 785, "name": "Solemn Soldier" },
    { "id": 786, "name": "Soul Binder" },
    { "id": 787, "name": "Summoning Scholar" },
    { "id": 788, "name": "Tech Golem" },
    { "id": 789, "name": "Treasure Brawler" },
    { "id": 790, "name": "Dire Lycan" },
    { "id": 791, "name": "Gourd Ghoul" },
    { "id": 792, "name": "Hollowed Minion" },
    { "id": 793, "name": "Bonbon Gummy Globlin" },
    { "id": 794, "name": "Maize Harvester" },
    { "id": 795, "name": "Spectral Butler" },
    { "id": 796, "name": "Teenage Vampire" },
    { "id": 797, "name": "Black Diamond Racer" },
    { "id": 798, "name": "Double Black Diamond Racer" },
    { "id": 799, "name": "Free Skiing" },
    { "id": 800, "name": "Young Prodigy Racer" },
    { "id": 801, "name": "Nitro Racer" },
    { "id": 802, "name": "Sporty Ski Instructor" },
    { "id": 803, "name": "Toboggan Technician" },
    { "id": 804, "name": "Rainbow Racer" },
    { "id": 805, "name": "Costumed Monkey" },
    { "id": 806, "name": "Cupcake Camo" },
    { "id": 807, "name": "Cupcake Candle Thief" },
    { "id": 808, "name": "Armored Archer" },
    { "id": 809, "name": "Dancing Assassin" },
    { "id": 810, "name": "Master of the Chi Belt" },
    { "id": 811, "name": "Student of the Chi Belt" },
    { "id": 812, "name": "Master of the Chi Claw" },
    { "id": 813, "name": "Student of the Chi Claw" },
    { "id": 814, "name": "Grand Master of the Dojo" },
    { "id": 815, "name": "Supreme Sensei" },
    { "id": 816, "name": "Dumpling Delivery" },
    { "id": 817, "name": "Master of the Chi Fang" },
    { "id": 818, "name": "Student of the Chi Fang" },
    { "id": 819, "name": "Ascended Elder" },
    { "id": 820, "name": "Shaolin Kung Fu" },
    { "id": 821, "name": "Wandering Monk" },
    { "id": 822, "name": "Shinobi" },
    { "id": 823, "name": "Militant Samurai" },
    { "id": 824, "name": "Enlightened Labourer" },
    { "id": 825, "name": "Wave Racer" },
    { "id": 826, "name": "Creepy Marionette" },
    { "id": 827, "name": "Sandmouse" },
    { "id": 828, "name": "Arcane Summoner" },
    { "id": 829, "name": "Meteorite Mover" },
    { "id": 830, "name": "Battering Ram" },
    { "id": 831, "name": "Cursed Taskmaster" },
    { "id": 832, "name": "Dawn Guardian" },
    { "id": 833, "name": "Mining Materials Manager" },
    { "id": 834, "name": "Night Shift Materials Manager" },
    { "id": 835, "name": "Hardworking Hauler" },
    { "id": 836, "name": "Mischievous Meteorite Miner" },
    { "id": 837, "name": "Mischievous Wereminer" },
    { "id": 838, "name": "Monster of the Meteor" },
    { "id": 839, "name": "Meteorite Golem" },
    { "id": 840, "name": "Meteorite Miner" },
    { "id": 841, "name": "Meteorite Mystic" },
    { "id": 842, "name": "Hypnotized Gunslinger" },
    { "id": 843, "name": "Meteorite Snacker" },
    { "id": 844, "name": "Night Watcher" },
    { "id": 845, "name": "Nightfire" },
    { "id": 846, "name": "Nightmancer" },
    { "id": 847, "name": "Reveling Lycanthrope" },
    { "id": 848, "name": "Wealthy Werewarrior" },
    { "id": 849, "name": "Alpha Weremouse" },
    { "id": 850, "name": "Werehauler" },
    { "id": 851, "name": "Wereminer" },
    { "id": 852, "name": "Joy" },
    { "id": 853, "name": "Great Winter Hunt Impostor" },
    { "id": 854, "name": "Frightened Flying Fireworks" },
    { "id": 855, "name": "Costumed Rooster" },
    { "id": 856, "name": "Sprinkly Sweet Cupcake Cook" },
    { "id": 857, "name": "Heart of the Meteor" },
    { "id": 858, "name": "Barmy Gunner" },
    { "id": 859, "name": "Bilged Boatswain" },
    { "id": 860, "name": "Cabin Boy" },
    { "id": 861, "name": "Corrupt Commodore" },
    { "id": 862, "name": "Dashing Buccaneer" },
    { "id": 863, "name": "Eggsquisite Entertainer" },
    { "id": 864, "name": "Tomb Exhumer" },
    { id: 865, name: "Absolute Acolyte" },
    { id: 866, name: "Chronomaster" },
    { id: 867, name: "Vigilant Ward" },
    { id: 868, name: "Portal Paladin" },
    { id: 869, name: "Epoch Golem" },
    { id: 870, name: "Timeslither Pythoness" },
    { id: 871, name: "Record Keeper" },
    { id: 872, name: "Record Keeper's Assistant" },
    { id: 873, name: "Timeless Lich" },
    { id: 874, name: "Sentient Slime" },
    { id: 875, name: "Chamber Cleaver" },
    { id: 876, name: "Harbinger of Death" },
    { id: 877, name: "Portal Plunderer" },
    { id: 878, name: "Skeletal Champion" },
    { id: 879, name: "Timelost Thaumaturge" },
    { id: 880, name: "Shackled Servant" },
    { id: 881, name: "Clockwork Timespinner" },
    { id: 882, name: "Portal Pursuer" },
    { id: 883, name: "Dread Knight" },
    { id: 884, name: "Carrion Medium" },
    { id: 885, name: "Artillery Commander" },
    { id: 886, name: "Charming Chimer" },
    { id: 887, name: "Cloud Collector" },
    { id: 888, name: "Cycloness" },
    { id: 889, name: "Dragoon" },
    { id: 890, name: "Fluttering Flutist" },
    { id: 891, name: "Ful'Mina, The Mountain Queen" },
    { id: 892, name: "Homeopathic Apothecary" },
    { id: 893, name: "Monsoon Maker" },
    { id: 894, name: "Nightshade Flower Girl" },
    { id: 895, name: "Nightshade Maiden" },
    { id: 896, name: "Rain Collector" },
    { id: 897, name: "Rainwater Purifier" },
    { id: 898, name: "Rain Wallower" },
    { id: 899, name: "Rainmancer" },
    { id: 900, name: "Spore Salesman" },
    { id: 901, name: "Rain Summoner" },
    { id: 902, name: "Thundering Watcher" },
    { id: 903, name: "Thunderlord" },
    { id: 904, name: "Thunder Strike" },
    { id: 905, name: "Violet Stormchild" },
    { id: 906, name: "Breeze Borrower" },
    { id: 907, name: "Windy Farmer" },
    { id: 908, name: "Wind Warrior" },
    { id: 909, name: "Wind Watcher" },
];

var mice = []

function crownType(node) {
    if (node.hasClass('gold')) { return 'gold'; }
    if (node.hasClass('silver')) { return 'silver'; }
    if (node.hasClass('bronze')) { return 'bronze'; }

    return 'none';
}

function addMouse(mouse) {
    var encountered = false;

    for (var i = 0; i < mice.length; i++) {
        var toCheck = mice[i];

        if (toCheck.id == mouse.id) {
            encountered = true;
        }
    }

    if (!encountered) {
        if (mouse.name.indexOf('Mousert') < 0) {
            mouse.name = mouse.name.replace(' Mouse', '')
        }
        mice.push(mouse)
    }
}

$('.mousebox').each(function(i, node) {
    var mouse = {
        name: $(node).find('img').attr('title'),
        catches: $(node).find('.numcatches').text(),
        crownType: crownType($(node).find('.numcatches'))
    }

    var parent = $(node).parent('.favoriteCrownToggle');

    if (parent.length > 0) {
        mouse.id = parent.data('mouse-id');
    } else {
        var uniq = $(node).find('img').attr('title');

        if (uniq == "Keeper Mouse") {
            mouse.id = 108;
        } else if (uniq == "Keeper") {
            mouse.id = 109;
        } else {
            allMice.forEach(function(m) {
                var mouseName = m.unique || m.name;
                if (mouseName == uniq || mouseName + " Mouse" == uniq) {
                    mouse.id = m.id;
                }
            });
        }

    }

    addMouse(mouse);
});

var remaining = $('select.remainingMouse option');

remaining.each(function(i, node) {
    var id = $(node).val();
    var text = $(node).text();

    if (id) {
        var mouse = {
            id: id,
            name: text.substring(0, text.lastIndexOf(' (')),
            catches: text.substring(text.lastIndexOf(' (') + 2, text.length - 1),
            crownType: 'none'
        }

        addMouse(mouse);
    }
});

allMice.forEach(function(allMouse) {
    var caught = false;

    mice.forEach(function(mouse) {
        if (mouse.id == allMouse.id) {
            caught = true;
            mouse.name = allMouse.name;
        }
    });

    if (!caught) {
        allMouse.catches = 0;
        addMouse(allMouse);
    }
});

//output


var mice = mice.sort(function(a, b) { return a.id - b.id; })

var label = "Found data for " + mice.length + " mice\n";
var output = "";


for (var i = 0; i < mice.length; i++) {
    var mouse = mice[i];
    output += mouse.id + "\t" + mouse.name + "\t" + mouse.catches + "\n";
}

var golds = mice.reduce(function(count, mouse) {
    return count + (mouse.crownType === "gold" ? 1 : 0);
}, 0);

var silvers = mice.reduce(function(count, mouse) {
    return count + (mouse.crownType === "silver" ? 1 : 0);
}, 0);

var bronze = mice.reduce(function(count, mouse) {
    return count + (mouse.crownType === "bronze" ? 1 : 0);
}, 0);

var total = golds + silvers + bronze;
var perc = (total / allMice.length) * 100;

var crownStat = function(label, count) {
    return "# of " + label + " Crowns: " + count + " (" + (count / allMice.length * 100).toFixed(2) + "%)";
}

var stats = crownStat("Gold", golds);
stats += "\n" + crownStat("Silver", silvers);
stats += "\n" + crownStat("Bronze", bronze);
stats += "\nTotal Crowns: " + total + "/" + allMice.length + " (" + (perc.toFixed(2)) + "%)";

stats += "\n\n" + crownStat("Century Club", silvers + golds);

$('.mhccOutput').remove();

var html = "<div class=\"mhccOutput\"><textarea style=\"width:48%;min-height: 250px;\">" + output + "</textarea><textarea style=\"width: 49%; min-height: 250px;\">" + stats + "</textarea></div>";


$('#overlayContainer .container #header').after($(html));
